### PR TITLE
Expand index.md

### PR DESCRIPTION
**Pull request by veddox**
I found the home page of articulate-lisp.com a little uninformative - it doesn't tell you all that terribly much about what the site is about. So I copy-pasted in (with some minor tweaks) your Github README text, which provides the sort of information I'd be looking for on a front page.

I was just a little confused by your use of the %-sign in the heading of index.md - that's not official Markdown, is it?

(I also amended the web-trotter walk-through page to mirror the new known-binary function.)

### CODE REVIEW

**Comment by pnathan** [comment]
Hi! 

Thank you so much for your contribution - :yellow_heart:  ! You should add your name to the list of contributors! Do you want to do that before I merge this PR?

This is actually [Pandoc-flavored markdown](http://pandoc.org/README.html#pandocs-markdown), combined with an entirely homebrew build tool `make.lisp`(it's in the root of the repository) which weaves together the content, headers, footers, and navbar.  I'm going to spend some time working on converting this to Jekyll, just for the sake of standardization and easy contribution.

**Comment by veddox** [comment]
You are most welcome :-) By "list of contributors", do you mean who.md or some other file?

**Comment by pnathan** [comment]
@veddox Yes, I do!

**Comment by veddox** [comment]
OK, ready for merging.

**Comment by pnathan** [comment]
merged. I'll run the `docker build && docker push` tonight when I get home from work.

**Comment by pnathan** [comment]
@veddox - deployed. :-)

**Pull request merged**
