### PR TITLE
Rewrote 'known-binary' function in web-trotter.lisp.

### PR DESCRIPTION
**Pull request by veddox**
Made the known-binary function more concise and readily extensible.

I don't know if you want/need this, but if you do, here you go ;-)

### CODE REVIEW

**Comment by pnathan** [comment]
Hey, I like it! Now to resurrect the build system. :-)

**Comment by veddox** [comment]
Sorry, I don't quite understand why the build fails - I only changed the trotter file :-(

**Comment by pnathan** [comment]
Sorry, I was unclear. The build system is not working quite right anymore,
I think.  I need to fix that (it's my problem).

**Comment by veddox** [comment]
oh, ok :D

**Comment by pnathan** [comment]
@veddox added your contributions and uploaded the build to the site.

**Comment by veddox** [comment]
great, thanks! I might send in some more stuff if I get around to it.

**Pull request merged**
