### PR TITLE
Refactor structure

### LINKED ISSUE #37: Implementations aren't "systems"
«Common Lisp implementations usually are called “systems”» says env/lisp-systems.html

That's the first time I hear of implementations called "systems". They are usually "implementations", or when the OS (and optionally CPU) is also specified, "platform". I would remove that remark and rename the page.

A link from implementation to implementation-specific page in that page would be nice.

### PR DESCRIPTION
**Pull request by mordocai**
This completely refactors the file and menu structure of the site. 

My feeling is that this new structure is not ideal but is better than the current.

* The menu items are roughly ordered left-to-right in the order you use them.
* IDEs is broken out from env
* Implementations new category instead of env. This also partially fixes #37 
* Consistent capitalization
* Theoretically more noobie-friendly menu titles.

Two questions:

* What the should we call the quicklisp link? I like it up by itself, but i'm not sure if "Libraries" is really the right thing. Maybe packages? Idk, trying to be noobie friendly.
* LispWorks is an IDE and an implementation. Right now i'm solving this via symlinks (which git supports last I heard) but maybe there's a better way?

### CODE REVIEW

**Comment by pnathan** [comment]
Interesting. Any particular rationale for the reordering of the nav structure?

**Comment by mordocai** [comment]
The literal ordering rationale was simply  "The menu items are roughly ordered left-to-right in the order you use them.". It makes sense to me since western audiences read left to right.

As far as the reorganizing of categories(removing some, adding others) and such, it was mainly just based on what I felt made sense. No real hard reasons.

**Comment by mordocai** [comment]
Off to bed. I imagine this should be a discussion, let me know if you want to do IRC chat or even a call or something.

**Comment by pnathan** [comment]
@mordocai Somewhat. My heroic weakness is UX. If you're practiced at making sites easy to use and comfortable for newbies, I am happy to defer. I compared the two sites and I don't have a strong opinion.

**Comment by mordocai** [comment]
I don't consider myself great at UI but I have a friend who I do consider great at it. I'm going to have her take a look at both versions and offer suggestions

**Comment by pnathan** [comment]
The one thing is that I would like to ensure a highly information-driven aesthetic, with minimal "pop" and "flair"; just enough to smoothly and effectively communicate.

**Comment by mordocai** [comment]
Just to let you know, I haven't forgotten about this. My friend just hasn't had time to take a look yet.

**Comment by pnathan** [comment]
noted! I look forward to a design critique. :)

**Comment by veddox** [comment]
@mordocai, I like your revised structure of the site. I think the current menu, while no doubt functional, feels rather hacked up ("env" instead of "Lisp Environment" or some such, lower-case first letters). Your changes eliminate that and make the whole site more easily navigable. (I was confused by the menu myself when I first saw the site.)

@pnathan, I vote for adapting the menu.

**Comment by escarre** [comment]
@pnathan, I'm the friend mordocai mentioned! I understand the goal is straightforward-ness and clarity rather than "making it pop", and Chris's changes definitely help achieve that end. As a non-Lisper myself, I'm a great test subject, and I prefer the new menu structure. I vote for merging.

In an ideal world, I think the best case scenario would be a bit of a 'getting started guide' that culminated in the list of further resources. That said - this is a great start.

**Comment by pnathan** [comment]
ok!

**Comment by mordocai** [comment]
Hey, when do you expect this will be deployed to the live site? Just wondering because I want to double check everything on live since I'm paranoid.

**Comment by pnathan** [comment]
Good question... Probably by Sunday night.

**Comment by pnathan** [comment]
Hey, @mordocai , @veddox  and @escarre - Super sorry regarding the delay. Long story involving pnathan and his travails in DIY Linux. The Docker image is pushed and running.

**Comment by veddox** [comment]
@pnathan, great! I think I'll take a look at the CLisp page, it's the implementation I use so I should be able to write something about it...

**Comment by pnathan** [comment]
@veddox - thanks! Love to see it!

**Comment by veddox** [comment]
@pnathan I submitted a pull request. Let's switch the discussion over to the next thread ;-)

**Pull request merged**
