### PR TITLE
Libraries: dexador, some links, Awesome CL, State of CL 2015

### PR DESCRIPTION
**Pull request by vindarel**
In this PR I suggest:
- to replace drakma by dexador: http://quickdocs.org/dexador/ (better and sanier API, unicode handling, faster)
- I added some href links but not all
- I reference the Awesome-cl list and the State of CL ecosystem article, both very valuable and doing the same job has this list.

### CODE REVIEW

**Comment by pnathan** [comment]
Does dexador work on ABCL, CLISP, SBCL, ECL (or a lisp in that family), and CCL? I try to ensure the libraries up on a-c-l are pretty cross-implementation?

**Comment by vindarel** [comment]
Good point. I had to ask here: https://github.com/fukamachi/dexador/issues/27

**Comment by pnathan** [comment]
Also note that drakma is stupid easy to use: http-request and, voila, a
result. That is one reason why I dramatically like it. tbh I don't know how
easy dexador is.

**Comment by vindarel** [comment]
Dexador is also this easy, besides this presentation is pretty convincing: http://www.slideshare.net/fukamachi/dexador-rises (tbh I barely tried Drakma, but I was beaten by many CL libraries with weird/old/unsufficient design…).

**Comment by vindarel** [comment]
Hi, Fukamachi answered:

> I tested it with SBCL, ABCL, ECL and CCL.
Since Dexador uses usocket as its backend, I expect it's portable enough like Drakma.

Is that enough or I keep a reference to Drakma ? ("Dexador… that aims at replacing Drakma)

**Pull request merged**
