### PR TITLE
Expand CLISP entry, update About page

### PR DESCRIPTION
**Pull request by veddox**
I wrote something on CLISP and added all the other contributors to the About page.

### CODE REVIEW

**Comment by veddox** [comment]
@pnathan OK, added those distros.

**Comment by mordocai** [comment]
For what it is worth, I like this. The description of each implementation seems very similar to the others though, it'll probably be worth writing a "use case" focused article where someone knowledgeable on the differences (aka not me) compares and contrasts the uses of each implementation.

I've been thinking of making a post on /r/lisp requesting help gathering raw info which then we could distill into nice web pages.

**Comment by veddox** [comment]
@mordocai, sounds like two good ideas! We do recommend SBCL for beginners, but a side-by-side comparison of the various implementations would be very useful.

**Comment by pnathan** [comment]
Love the ideas! Keep the PRs coming. :-)

**Pull request merged**
