### PR TITLE
Portacle, the portable and multiplatform dev environment

### PR DESCRIPTION
**Pull request by vindarel**
the easiest and quickest way to get started !

### CODE REVIEW

**Comment by pnathan** [comment]
I'll deploy this tonight when I get home. If you don't see it by tomorrow morning Seattle time, remind me on this PR to stop being lazy.

**Comment by vindarel** [comment]
what's Seattle time zone btw ? 

(nice reminder isn't it ?)

**Comment by pnathan** [comment]
whooops. :-/ Sorry. I'll chase this after work today & if I have time, try
to cadge together a "deploy on merge" system. That's the Proper way to do
it. :)

**Comment by vindarel** [comment]
You don't want to use github pages btw ? It's an easy solution.

**Pull request merged**
